// <auto-generated />
using System;
using CryptoWallet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoWallet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414211715_AddSeedDatav2")]
    partial class AddSeedDatav2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("CryptoWallet.Models.CryptoAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CryptoAssets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PurchaseDate = new DateTime(2026, 4, 14, 21, 17, 14, 905, DateTimeKind.Utc).AddTicks(5853),
                            PurchasePrice = 60000m,
                            Quantity = 0.5m,
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 2,
                            PurchaseDate = new DateTime(2026, 4, 14, 21, 17, 14, 905, DateTimeKind.Utc).AddTicks(5862),
                            PurchasePrice = 3000m,
                            Quantity = 4m,
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 3,
                            PurchaseDate = new DateTime(2026, 4, 14, 21, 17, 14, 905, DateTimeKind.Utc).AddTicks(5863),
                            PurchasePrice = 66000m,
                            Quantity = 0.1m,
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 4,
                            PurchaseDate = new DateTime(2026, 4, 14, 21, 17, 14, 905, DateTimeKind.Utc).AddTicks(5864),
                            PurchasePrice = 120m,
                            Quantity = 25m,
                            Symbol = "SOL"
                        },
                        new
                        {
                            Id = 5,
                            PurchaseDate = new DateTime(2026, 4, 14, 21, 17, 14, 905, DateTimeKind.Utc).AddTicks(5865),
                            PurchasePrice = 55000m,
                            Quantity = 0.3m,
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 6,
                            PurchaseDate = new DateTime(2026, 4, 14, 21, 17, 14, 905, DateTimeKind.Utc).AddTicks(5866),
                            PurchasePrice = 1900m,
                            Quantity = 5m,
                            Symbol = "ETH"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
