// <auto-generated />
using System;
using CryptoWallet.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoWallet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414210717_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("CryptoWallet.Models.CryptoAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CryptoAssets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PurchaseDate = new DateTime(2026, 4, 14, 21, 7, 16, 994, DateTimeKind.Utc).AddTicks(2767),
                            PurchasePrice = 60000m,
                            Quantity = 0.5m,
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 2,
                            PurchaseDate = new DateTime(2026, 4, 14, 21, 7, 16, 994, DateTimeKind.Utc).AddTicks(2773),
                            PurchasePrice = 3000m,
                            Quantity = 4m,
                            Symbol = "ETH"
                        },
                        new
                        {
                            Id = 3,
                            PurchaseDate = new DateTime(2026, 4, 14, 21, 7, 16, 994, DateTimeKind.Utc).AddTicks(2775),
                            PurchasePrice = 66000m,
                            Quantity = 0.1m,
                            Symbol = "BTC"
                        },
                        new
                        {
                            Id = 4,
                            PurchaseDate = new DateTime(2026, 4, 14, 21, 7, 16, 994, DateTimeKind.Utc).AddTicks(2776),
                            PurchasePrice = 120m,
                            Quantity = 25m,
                            Symbol = "SOL"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
